environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '9'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - node --version
  - npm --version
  - npm run test

build: off
